<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE roms [
<!ELEMENT roms (rom)+>
<!ENTITY deg "&#176;">
<!-- degree sign --><!ENTITY micro "&#181;">
<!-- micro sign --><!ELEMENT rom (romid , table+)>
<!ATTLIST rom base CDATA #IMPLIED>
<!ELEMENT romid (xmlid , internalidaddress , internalidstring , caseid? , ecuid , year , market , make , model , submodel , transmission , flashmethod? , memmodel , filesize , obsolete?)>
<!ELEMENT xmlid (#PCDATA)>
<!ELEMENT internalidaddress (#PCDATA)>
<!ELEMENT internalidstring (#PCDATA)>
<!ELEMENT caseid (#PCDATA)>
<!ELEMENT ecuid (#PCDATA)>
<!ELEMENT year (#PCDATA)>
<!ELEMENT market (#PCDATA)>
<!ELEMENT make (#PCDATA)>
<!ELEMENT model (#PCDATA)>
<!ELEMENT submodel (#PCDATA)>
<!ELEMENT transmission (#PCDATA)>
<!ELEMENT flashmethod (#PCDATA)>
<!ELEMENT memmodel (#PCDATA)>
<!ELEMENT filesize (#PCDATA)>
<!ELEMENT obsolete (#PCDATA)>
<!ELEMENT table (#PCDATA | scaling | table | description | data | state)*>
<!ATTLIST table type NMTOKENS #IMPLIED>
<!ATTLIST table name CDATA #IMPLIED>
<!ATTLIST table category CDATA #IMPLIED>
<!ATTLIST table storagetype CDATA #IMPLIED>
<!ATTLIST table endian (little | big) #IMPLIED>
<!ATTLIST table sizex CDATA #IMPLIED>
<!ATTLIST table sizey CDATA #IMPLIED>
<!ATTLIST table userlevel (1 | 2 | 3 | 4 | 5) #IMPLIED>
<!ATTLIST table logparam CDATA #IMPLIED>
<!ATTLIST table storageaddress CDATA #IMPLIED>
<!ELEMENT scaling EMPTY>
<!ATTLIST scaling units CDATA #REQUIRED>
<!ATTLIST scaling expression CDATA #REQUIRED>
<!ATTLIST scaling to_byte CDATA #REQUIRED>
<!ATTLIST scaling format CDATA #REQUIRED>
<!ATTLIST scaling fineincrement CDATA #REQUIRED>
<!ATTLIST scaling coarseincrement CDATA #REQUIRED>
<!ELEMENT description (#PCDATA)>
<!ELEMENT data (#PCDATA)>
<!ELEMENT state (#PCDATA)>
<!ATTLIST state name CDATA #REQUIRED>
<!ATTLIST state data CDATA #REQUIRED>
]>
<roms>

<rom> <!--Extended Load MS43 BASE-->
      <!--
v0
	- draft of MS43

	In this BASE section define all the common table data and axis attributes.
    Leave out the ROM specific addresses.
-->
      <romid>
         <xmlid>BMWMS43BASE-extload</xmlid>
         <ecuid>1234567</ecuid>
         <year>2001-2006</year>
         <market>USDM</market>
         <make>BMW</make>
         <model>E46/E39/Z3/X5</model>
         <submodel>MS43</submodel>
         <transmission>MT/AT</transmission>
         <memmodel>SAK-C167CR-LM</memmodel>
         <filesize>512kb</filesize>
      </romid>
	  
<!--Config Switches-->
	<table type="Switch" name="O2 Sensor Configuration" category="Configurations" sizey="1">
		<state name="Single Bank, Auto learning of post CAT O2 Sensor" data="0"/>
		<state name="Single Bank, with 1 post CAT O2 Sensor" data="2"/>
		<state name="Twin Bank, Auto learning of post CAT O2 Sensors" data="1"/>
		<state name="Twin Bank, with 2 Post CAT O2 Sensors" data="4"/>
		<state name="Twin Bank, with 1 Post CAT O2 Sensor" data="3"/>
		<description>This switch changes the O2 sensor configuration, useful for turbocharged applications. Auto learning will detect if or how many post cat O2 sensors are plugged in after clearing "learned variants" using INPA</description>
    </table>
	<table type="Switch" name="Secondary Air pump config" category="Configurations" sizey="1" userlevel="1">
		<state name="0" data="00"/>
		<state name="1" data="01"/>	
		<description>For forced OBD readiness, set to 1.</description>
	</table>
    <table type="Switch" name="MIL" category="Configurations" sizey="1" userlevel="1">
		<state name="0" data="00"/>
		<state name="1" data="01"/>
		<state name="2" data="02"/>
		<state name="3" data="03"/>			
		<description>Malfunction Indicator Light. For forced OBD readiness, set to 2.</description>
	</table>
    <table type="Switch" name="MIL FUS" category="Configurations" sizey="1" userlevel="1">
		<state name="0" data="00"/>
		<state name="1" data="01"/>	
		<description>Malfunction Indicator Light fus.</description>
	</table>
    <table type="Switch" name="MIL EU2" category="Configurations" sizey="1" userlevel="1">
		<state name="0" data="00"/>
		<state name="1" data="01"/>
		<state name="2" data="02"/>
		<state name="3" data="03"/>			
		<description>Malfunction Indicator Light EU2. For forced OBD readiness, set to 2.</description>
	</table>
    <table type="Switch" name="Exhaust flap config" category="Configurations" sizey="1" userlevel="1">
		<state name="Enable" data="01"/>
		<state name="Disable" data="00"/>	
		<description>Exhaust flap.</description>
	</table>
    <table type="Switch" name="Electronic cooling fan" category="Configurations" sizey="1" userlevel="1">
		<state name="Enable" data="01"/>
		<state name="Disable" data="00"/>	
		<description>Electronic cooling fan.</description>
	</table>

    <table type="Switch" name="Brake Light Test Switch" category="Configurations" sizey="1" userlevel="1">
		<state name="Enable" data="02"/>
		<state name="Disable" data="00"/>	
		<description>Brake Light Test Switch - Disable to enable brake boosting without throwing a DTC</description>
	</table>
		
	<!--Fuel/Ignition - Axis-->
    <table type="2D" name="Basic Ignition Load Axis" category="Fuel/Ignition Timing - Axis" storagetype="uint16" sizex="12" endian="little" userlevel="1">
		<scaling units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0.00" fineincrement=".01" coarseincrement=".1"/>
			<table type="Static Y Axis" name="Columns" sizex="12">
				<data> 1</data>
				<data> 2</data>
				<data> 3</data>
				<data> 4</data>
				<data> 5</data>
				<data> 6</data>
				<data> 7</data>
				<data> 8</data>
				<data> 9</data>
				<data> 10</data>
				<data> 11</data>
				<data> 12</data>
			</table>
		<description>This axis is used in the basic timing map. Changes to this will require immediate reloading of the tuned file.</description>
    </table>
	
	<table type="2D" name="Basic Ignition RPM Axis" category="Fuel/Ignition Timing - Axis" storagetype="uint16" sizey="16" endian="little" userlevel="1">
		<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			<table type="Static Y Axis" name="Rows" sizey="16">
				<data>1</data>
				<data>2</data>
				<data>3</data>
				<data>4</data>
				<data>5</data>
				<data>6</data>
				<data>7</data>
				<data>8</data>
				<data>9</data>
				<data>10</data>
				<data>11</data>
				<data>12</data>
				<data>13</data>
				<data>14</data>
				<data>15</data>
				<data>16</data>
			</table>
		<description>This axis is used in the basic timing map. Changes to this will require immediate reloading of the tuned file.</description>
    </table>
	
    <table type="2D" name="Main Ignition Load Axis" category="Fuel/Ignition Timing - Axis" storagetype="uint16" sizex="16" endian="little" userlevel="1">
		<scaling units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0.00" fineincrement=".01" coarseincrement=".1"/>
			<table type="Static Y Axis" name="Columns" sizex="16">
				<data>1</data>
				<data>2</data>
				<data>3</data>
				<data>4</data>
				<data>5</data>
				<data>6</data>
				<data>7</data>
				<data>8</data>
				<data>9</data>
				<data>10</data>
				<data>11</data>
				<data>12</data>
				<data>13</data>
				<data>14</data>
				<data>15</data>
				<data>16</data>
			</table>
		<description>This axis is used in the main timing maps. Changes to this will require immediate reloading of the tuned file.</description>
    </table>
	
	<table type="2D" name="Main Ignition RPM Axis" category="Fuel/Ignition Timing - Axis" storagetype="uint16" sizey="20" endian="little" userlevel="1">
		<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			<table type="Static Y Axis" name="Rows" sizey="20">
				<data>1</data>
				<data>2</data>
				<data>3</data>
				<data>4</data>
				<data>5</data>
				<data>6</data>
				<data>7</data>
				<data>8</data>
				<data>9</data>
				<data>10</data>
				<data>11</data>
				<data>12</data>
				<data>13</data>
				<data>14</data>
				<data>15</data>
				<data>16</data>
				<data>17</data>
				<data>18</data>
				<data>19</data>
				<data>20</data>
			</table>
		<description>This axis is used in the main timing maps. Changes to this will require immediate reloading of the tuned file.</description>
    </table>
	
    <table type="2D" name="Main Fuel Load Axis" category="Fuel/Ignition Timing - Axis" storagetype="uint16" sizex="12" endian="little" userlevel="1">
		<scaling units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0.00" fineincrement=".01" coarseincrement=".1"/>
			<table type="Static Y Axis" name="Columns" sizex="12">
				<data> 1</data>
				<data> 2</data>
				<data> 3</data>
				<data> 4</data>
				<data> 5</data>
				<data> 6</data>
				<data> 7</data>
				<data> 8</data>
				<data> 9</data>
				<data> 10</data>
				<data> 11</data>
				<data> 12</data>
			</table>
		<description>This axis is used in the main fuel maps. Changes to this will require immediate reloading of the tuned file.</description>
    </table>
	
    <table type="2D" name="Main Fuel RPM Axis" category="Fuel/Ignition Timing - Axis" storagetype="uint16" sizey="16" endian="little" userlevel="1">
		<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			<table type="Static Y Axis" name="Rows" sizey="16">
				<data> 1</data>
				<data> 2</data>
				<data> 3</data>
				<data> 4</data>
				<data> 5</data>
				<data> 6</data>
				<data> 7</data>
				<data> 8</data>
				<data> 9</data>
				<data> 10</data>
				<data> 11</data>
				<data> 12</data>
				<data> 13</data>
				<data> 14</data>
				<data> 15</data>
				<data> 16</data>
			</table>
		<description>This axis is used in the main fuel maps. Changes to this will require immediate reloading of the tuned file.</description>
    </table>

<!--Calculated Fuel-->

	<table type="2D" name="Injector Flow" category="Calculated Fuel" storagetype="uint16" endian="little" sizey="1" userlevel="5">
		<scaling units="cm^3" expression="x" to_byte="x" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="Y Axis" name="Injector Flow" storagetype="uint16" endian="little">
				<scaling units="cm^3" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
					<data> - </data>
			</table>
		<description>Injector flow rate in cm³/min at 3.5 bar</description>
	</table>
   
	<table type="2D" name="Fuel Density" category="Calculated Fuel" storagetype="uint16" endian="little" sizey="1" userlevel="5">
		<scaling units="kg/dm3" expression="x*0.000030517578125" to_byte="x/0.000030517578125" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="Y Axis" name="Fuel Density" storagetype="uint16" endian="little">
				<scaling units="kg/dm3" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
					<data> - </data>
			</table>
		<description>Fuel density in kg/dm³

			Common fuel densities:	
			Gasoline 0,72 - 0,78
			E85 0,77 - 0,79
		</description>
	</table>

	<table type="2D" name="Air/Fuel Ratio - Stoich" category="Calculated Fuel" storagetype="uint8" endian="little" sizey="1" userlevel="5">
		<scaling units="AFR" expression="x*0.1" to_byte="x/0.1" format="0.00" fineincrement=".01" coarseincrement="1"/>
			<table type="Y Axis" name="AFR" storagetype="uint16" endian="little">
				<scaling units="AFR" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
					<data> - </data>
			</table>
		<description>Stoichiometric air fuel ratio</description>
	</table>  
   
	<table type="3D" name="Fuel Scalar - Idle - Cold" category="Calculated Fuel" storagetype="uint16" endian="little" sizex="6" sizey="6" userlevel="5">
		<scaling units="Fuel Scaling %" expression="(x*0.0030517578125)-100" to_byte="(x+100)/0.0030517578125" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for idle fuel - cold engine. Log STFT and increase or decrease the values in this table to match the trims.</description>
    </table>
	
    <table type="3D" name="Fuel Scalar - Idle - Warm" category="Calculated Fuel" storagetype="uint16" endian="little" sizex="6" sizey="6" userlevel="5">
		<scaling units="Fuel Scaling %" expression="(x*0.0030517578125)-100" to_byte="(x+100)/0.0030517578125" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for idle fuel - warm engine. Log STFT and increase or decrease the values in this table to match the trims. </description>
    </table>
   
     <table type="3D" name="Fuel Scalar - Bank 1 Cold" category="Calculated Fuel" storagetype="uint16" endian="little" sizex="12" sizey="16" userlevel="5">
		<scaling units="Fuel Scaling %" expression="(x*0.0030517578125)-100" to_byte="(x+100)/0.0030517578125" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 1 on a cold engine, vanos active. Log STFT and increase or decrease the values in this table to match the trims.</description>
    </table>
      
	<table type="3D" name="Fuel Scalar - Bank 2 Cold" category="Calculated Fuel" storagetype="uint16" endian="little" sizex="12" sizey="16" userlevel="5">
		<scaling units="Fuel Scaling %" expression="(x*0.0030517578125)-100" to_byte="(x+100)/0.0030517578125" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 2 on a cold engine, vanos active. Log STFT and increase or decrease the values in this table to match the trims.</description>
    </table>
	
    <table type="3D" name="Fuel Scalar - Bank 1 Warm" category="Calculated Fuel" storagetype="uint16" endian="little" sizex="12" sizey="16" userlevel="5">
		<scaling units="Fuel Scaling %" expression="(x*0.0030517578125)-100" to_byte="(x+100)/0.0030517578125" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 1 on a warm engine, vanos active. Log STFT and increase or decrease the values in this table to match the trims.</description>
    </table>
	
    <table type="3D" name="Fuel Scalar - Bank 2 Warm" category="Calculated Fuel" storagetype="uint16" endian="little" sizex="12" sizey="16" userlevel="5">
		<scaling units="Fuel Scaling %" expression="(x*0.0030517578125)-100" to_byte="(x+100)/0.0030517578125" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 2 on a warm engine, vanos active. Log STFT and increase or decrease the values in this table to match the trims.</description>
    </table>  

	
<!--Fuel-->
	
   #BA114
	<table type="2D" name="WOT Detection" category="Fuel" storagetype="uint8" endian="little" sizey="16" userlevel="1">
		<scaling units="TPS" expression="x*0.46862745" to_byte="x/0.46862745" format="0.0" fineincrement=".1" coarseincrement="1"/>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>When this threshold is exceeded the injection will operate in open loop and the full load enrichment map is applied to the injection time.</description>
   </table>

    <table type="3D" name="Fuel Injection - Base (VANOS Fault)" category="Fuel" storagetype="uint16" endian="little" sizex="12" sizey="16" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>This is the injection map used when vanos is faulted</description>
    </table>
	
    <table type="2D" name="Full Load Enrichment" category="Fuel" storagetype="uint8" endian="little" sizex="16" userlevel="1">
		<scaling units="%" expression="((x*0.0039058823)-0.5)*100" to_byte="((x/100)+0.5)/0.0039058823" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>This is the full load enrichment map</description>
    </table>
	
    <table type="3D" name="Fuel Injection part load bank 1 cold engine" category="Fuel" storagetype="uint16" endian="little" sizex="12" sizey="16" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 2 on a cold engine, vanos active.</description>
    </table>
      
	<table type="3D" name="Fuel Injection part load bank 2 cold engine" category="Fuel" storagetype="uint16" endian="little" sizex="12" sizey="16" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 2 on a cold engine, vanos active.</description>
    </table>
	
    <table type="3D" name="Fuel Injection part load bank 1 warm engine" category="Fuel" storagetype="uint16" endian="little" sizex="12" sizey="16" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 2 on a warm engine, vanos active.</description>
    </table>
	
    <table type="3D" name="Fuel Injection part load bank 2 warm engine" category="Fuel" storagetype="uint16" endian="little" sizex="12" sizey="16" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 2 on a warm engine, vanos active.</description>
    </table>
      
	<table type="3D" name="Fuel Injection idlespeed cold engine" category="Fuel" storagetype="uint16" endian="little" sizex="6" sizey="6" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 2 on a warm engine, vanos active.</description>
    </table>
	
    <table type="3D" name="Fuel Injection idlespeed warm engine" category="Fuel" storagetype="uint16" endian="little" sizex="6" sizey="6" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Load" storagetype="uint16" endian="little" logparam="E2">
				<scaling name="Metric" units="mg/stroke" expression="x*0.04239" to_byte="x/0.04239" format="0" fineincrement="1" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Engine Speed" storagetype="uint16" endian="little" logparam="P8">
				<scaling units="RPM" expression="x" to_byte="x" format="#" fineincrement="50" coarseincrement="100"/>
			</table>
		<description>Injection map for bank 2 on a warm engine, vanos active.</description>
    </table>

	#BA114
    <table type="2D" name="Fuel Injector Dead Time" category="Fuel" storagetype="uint8" endian="little" sizey="8" userlevel="1">
		<scaling units="milliseconds" expression="x*.032" to_byte="x/.032" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="Y Axis" name="Battery Voltage" storagetype="uint8" endian="little" logparam="">
				<scaling units="Volts" expression="x*.10196" to_byte="x/.10196" format="0.0" fineincrement="1" coarseincrement="10"/>
			</table>
		<description>Fuel Injector Dead Time correction.</description>
    </table>
	
    <table type="2D" name="Prestart Injection Time" category="Fuel" storagetype="uint16" endian="little" sizex="8" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.000" fineincrement=".1" coarseincrement="1"/>
			<table type="Y Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">
				<scaling name="Metric" units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
				<scaling name="Imperial" units="°F" expression="(x*.75-48)*1.8+32" to_byte="((x-32)/1.8+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
		<description>empty</description>
    </table>
	
	<table type="2D" name="T_TI_AS[CYL]" category="Fuel" storagetype="uint8" sizex="6" endian="little" userlevel="1">
		<scaling units="Injection factor" expression="x*0.0078125" to_byte="x/0.0078125" format="0.000" fineincrement="0.0078125" coarseincrement="0.0078125"/>
			<table type="Static Y Axis" name="Cylinder" sizex="6">
				<data>1</data>
				<data>2</data>
				<data>3</data>
				<data>4</data>
				<data>5</data>
				<data>6</data>
			</table>
		<description>Injection time mulitplier</description>
    </table>

	<table type="2D" name="Minimum Injection Time cylinder wall rewetting slow" category="Fuel" storagetype="uint16" sizey="4" endian="little" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.000" fineincrement=".01" coarseincrement=".1"/>
			<table type="Y Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">
				<scaling name="Metric" units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
				<scaling name="Imperial" units="°F" expression="(x*.75-48)*1.8+32" to_byte="((x-32)/1.8+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
		<description>empty</description>
    </table>
      
	<table type="2D" name="Minimum Injection Time cylinder wall rewetting fast" category="Fuel" storagetype="uint16" sizey="4" endian="little" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.000" fineincrement=".01" coarseincrement=".1"/>
			<table type="Y Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">
				<scaling name="Metric" units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
				<scaling name="Imperial" units="°F" expression="(x*.75-48)*1.8+32" to_byte="((x-32)/1.8+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
		<description>empty</description>
    </table>
      
	<table type="2D" name="Minimum Injection Time" category="Fuel" storagetype="uint16" sizex="1" endian="little" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.000" fineincrement=".01" coarseincrement=".1"/>
			<table type="Static Y Axis" name="Columns" sizex="1">
				<data> 1</data>
			</table>
		<description>This table adjust the minimum injection time, important to change when adding larger injectors.</description>
    </table>      
    
	<table type="3D" name="Afterstart Enrichment" category="Fuel" storagetype="uint8" endian="little" sizex="8" sizey="2" userlevel="1">
		<scaling units="Factor (multiplier)" expression="x*0.015625" to_byte="x/0.015625" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">
				<scaling name="Metric" units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
				<scaling name="Imperial" units="°F" expression="(x*.75-48)*1.8+32" to_byte="((x-32)/1.8+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
			<table type="Y Axis" name="Intake Temp" storagetype="uint8" endian="little" logparam="P11">
				<scaling units="°C" expression="x*.75-48" to_byte="(x+48)/.75" format="0.0" fineincrement="2" coarseincrement="10"/>
			</table>
		<description>This map is for Afterstart enrichment and used in conjunction with Gradual Reduction after Engine Start as a mulitplier to cold/warm fuel maps</description>
    </table>
      
	<table type="3D" name="Cranking Fuel at Cold Engine Start" category="Fuel" storagetype="uint16" endian="little" sizex="8" sizey="3" userlevel="1">
		<scaling units="Injector Pulsewidth (milliseconds)" expression="x*0.0053333333" to_byte="x/0.0053333333" format="0.00" fineincrement=".1" coarseincrement="1"/>
			<table type="X Axis" name="Coolant Temp" storagetype="uint8" endian="little" logparam="P2">